### ISSUE TITLE
Make the table on browser pretty. 

### ISSUE THREAD

**Issue by yankeexe** [yankeexe/good-first-issues#1]
Right now the table looks a bit off. 
Need to make it look good. 
Template can be found [here](https://github.com/yankeexe/good-first-issues/blob/f5953bd66b6783034eb2e886e774a331d199318e/gfi/utils/__init__.py#L133).

![image](https://user-images.githubusercontent.com/13623913/94553958-08fc8f80-0279-11eb-90bb-468e4d287fa2.png)

**Comment by SandarvaShakya** [comment]
I will take this issue.
