### ISSUE TITLE
Add `--hacktoberfest` flag to search issues based on udpated Hacktoberfest maintainer opt-in rule.

### ISSUE THREAD

**Issue by yankeexe** [yankeexe/good-first-issues#13]
While the philosophy behind the CLI remains on finding **good-first-issues**, it also aims to assist as a reliable tool during the Hacktoberfest. 

To keep updated with the new changes, introduce a new flag `--hacktoberfest` and abbreviation `--hf` flag to fetch issues based on the new **[Hacktoberfest maintainer opt-in rule](https://hacktoberfest.digitalocean.com/hacktoberfest-update)**.

The new rule implies: 
1. Repo should have `hacktoberfest` as topic. 
2. Issues should have `hacktoberfest-accepted` label.

**Comment by renugasaraswathy** [comment]
Hi @yankeexe, I would like to work on this issue. Could you assign it to me? 

Thanks

**Comment by yankeexe** [comment]
hey @renugasaraswathy sure. 🙂

**Comment by yankeexe** [comment]
Also @renugasaraswathy you can work only on the `graphql` API since REST API will be depricated on the next major Release.

**Comment by renugasaraswathy** [comment]
sure @yankeexe 
Thanks

**Comment by renugasaraswathy** [comment]
Hi @yankeexe, in [hacktoberfest update](https://hacktoberfest.digitalocean.com/hacktoberfest-update), they mentioned 

- repositories with topic "hacktoberfest" 
- PR to be labelled as "hacktoberfest-accepted" (not issues)

So for this issue, could you confirm my understanding listed below

1. ``gfi gql "rust-lang" --hacktoberfest``

- lists all repositories in the organization with topic "hacktoberfest"

2. ``gfi gql "sindresorhus" --user  --hacktoberfest``

- lists all repositories in a user profile with topic "hacktoberfest"

3. ``gfi gql "rust-lang" --repo "rust  --hacktoberfest"``

- as we are already searching by repo name, --hacktoberfest tag cannot be used here.

Please let me know if anything else to be covered.
Thanks

**Comment by yankeexe** [comment]
Hi @renugasaraswathy thank you for pointing this out, I understood the new rule about `hacktoberfest-accepted` label wrong. 

Yes your understanding is right, we can just go with checking the repo label with `hacktoberfest` and issues labeled with `good-first-issue` for the `--hacktoberfest` flag. 

And for number 3, should  we check for the label on repo and if it's not there, return some message? What do you think could be the right approach?

**Comment by renugasaraswathy** [comment]
@yankeexe for number 3, I think high preference needs to be given to '--repo' and list all issues in the repo. 

If the repo has topic 'hacktoberfest', approved/merged PR to any open issue will be considered for Hacktoberfest irrespective of labels given on the issues. 

Also not all maintainers add 'hacktoberfest' label to individual issues, so filter issues by 'hacktoberfest' label in a repo may not be useful.

**Comment by yankeexe** [comment]
@renugasaraswathy  yeah that sounds right, Then let's just skip the `--hacktoberfest` flag option with `--repo` flag.  We should add a warning and help message that clearly states it cannot be used with the `--repo`  flag. 🙂

**Comment by renugasaraswathy** [comment]
@yankeexe Sure will do that.

**Comment by renugasaraswathy** [comment]
Hi @yankeexe,

Done with the feedback. Please review the [pull request](https://github.com/yankeexe/good-first-issues/pull/14). 

![image](https://user-images.githubusercontent.com/5791109/95414582-d4a96300-094b-11eb-84a8-7ee0c2c1128e.png)
