### ISSUE TITLE
Fetch GitHub Personal Access Token from Environment variable

### ISSUE THREAD

**Issue by yankeexe** [yankeexe/good-first-issues#16]
The `check_credential`  function should check for the environment variable `GFITOKEN` else look for the config file.
Env variable should be of higher priority than the config file stored at `~/.gfi/good-first-issues`

**https://github.com/yankeexe/good-first-issues/blob/207c5f3fd121fb25bb53830b813e5fb0286bc1b8/good_first_issues/utils/__init__.py#L41**

---

**_What will this feature enable?_**
This will enable the **containerization** of the CLI that can be used with environment variable for making requests.

**Comment by mrunderline** [comment]
I think it can done with module [python-dotenv](https://pypi.org/project/python-dotenv/ ) are you agree to use it?

**Comment by yankeexe** [comment]
@mrunderline yes, are you willing to work on this?
