### ISSUE TITLE
Add pytest to requirements

### ISSUE THREAD

**Issue by asuzukosi** [yankeexe/good-first-issues#21]
Pytest is not part of the requirements of the project i want to add pytest to the root requirements.txt file

**Comment by yankeexe** [comment]
Pytest has been added to setup.py `requirements_dev` variable. https://github.com/yankeexe/good-first-issues/blob/ec31f0b8d6eadaaeda3e692e95f9a8a9d2befa48/setup.py#L8

You can run `make setup` to install it.
