### ISSUE TITLE
when I try it in windows10  there are error called ```  Error: Bad credentials.```

### ISSUE THREAD

**Issue by GAbdulWahab** [yankeexe/good-first-issues#24]

**Comment by yankeexe** [comment]
@GAbdulWahab can you post a screenshot or error logs.

**Comment by GAbdulWahab** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/101266265/162004050-23eb5b38-ff56-4d81-81e5-581c1712dc87.jpg)

**Comment by yankeexe** [comment]
@GAbdulWahab Try creating your GitHub tokens from here: 
https://github.com/settings/tokens and provide access for repos.
