### ISSUE TITLE
Create a code of conduct file 

### ISSUE THREAD

**Issue by Ayush0431** [yankeexe/good-first-issues#25]
Create a code of conduct file.....assign me this issue and i will make a pr for this issue .

**Comment by shoc71** [comment]
hey I was just thinking the same thing and here you go for your code of conduct file as the backbone (with further modifications) 
[Code of Conduct for Coders.txt](https://github.com/yankeexe/good-first-issues/files/11360358/Code.of.Conduct.for.Coders.txt)

**Comment by amoghak-ds** [comment]
I'd like to make and update the "code of conduct" file, can you please assign it to me?

**Comment by geetanj16** [comment]
Can you assign me this issue?

**Comment by amoghakancharla** [comment]
@geetanj16 You can go ahead and work on it.
