### ISSUE TITLE
Error when installing good-first-issues

### ISSUE THREAD

**Issue by NegiBaba** [yankeexe/good-first-issues#29]
When I run the given command in the terminal I get an error (see image)
<img width="1202" alt="Screenshot 2023-09-02 at 12 12 04 AM" src="https://github.com/yankeexe/good-first-issues/assets/48850319/c4586430-0613-405a-9193-b39b8e02ee24">

Am I doing something wrong?

**Comment by yankeexe** [comment]
@NegiBaba what python version are you using?

**Comment by agaluscondev** [comment]
I'm getting the same issue. I have the following versions:
```➜  ~ python3 -V
Python 3.11.4
➜  ~ pip3 -V
pip 23.2.1 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
```

**Comment by lekhana3003** [comment]
I am getting the same issue for python3.9 but no issue for python3.10

**Comment by yankeexe** [comment]
@agaluscondev that should not be the case now. 
Can you please try again?

**Comment by yankeexe** [comment]
@lekhana3003 
Tested with `Python 3.9.13` and I see no issues.

**Comment by agaluscondev** [comment]
@yankeexe Tested it with 3.12.3 and it seems to work fine there. Thanks!
