### ISSUE TITLE
Handle "port already in use error" when using `--web` flag.v / Dynamic Port allocation.

### ISSUE THREAD

**Issue by yankeexe** [yankeexe/good-first-issues#3]
Display proper error message when port is already used.
**Dynamic Port Allocation using `Port 0` auto allocation.**

**Method reference:**
 https://github.com/yankeexe/good-first-issues/blob/e30a0e7a3cdbda1b1514cb8c210170a4569d093c/gfi/utils/__init__.py#L92

**Error right now:**

![issues](https://user-images.githubusercontent.com/13623913/94567435-30f4ee80-028b-11eb-8166-64144bc75de5.png)

**Comment by Alig1493** [comment]
I can take a look at this issue.
