### ISSUE TITLE
Auto open web browser if `--web` flag is passed.

### ISSUE THREAD

**Issue by yankeexe** [yankeexe/good-first-issues#4]
Use the [webbrowser](https://docs.python.org/3/library/webbrowser.html) built-in package to open the web browser automatically when `--web` flag is passed. 

**Method reference:** 
https://github.com/yankeexe/good-first-issues/blob/e30a0e7a3cdbda1b1514cb8c210170a4569d093c/gfi/utils/__init__.py#L92

---

**Currently just shows the port where the static page is served:** 
![image](https://user-images.githubusercontent.com/13623913/94568204-efb10e80-028b-11eb-9f4c-735fcebadb2c.png)

**Comment by anupamasok** [comment]
Looks like this issue is resolved

**Comment by yankeexe** [comment]
> Looks like this issue is resolved

Yes, it's being worked on #9 @anupamasok
